apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetest-takoyakidath
  labels:
    app: kubetest-takoyakidath
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubetest-takoyakidath
  template:
    metadata:
      labels:
        app: kubetest-takoyakidath
    spec:
      containers:
        - name: kubetest-takoyakidath
          image: registry.uniproject.jp/yuito-it/yuito-work:3.4.4
          ports:
            - containerPort: 3000
              name: default-port
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 20
            httpGet:
              path: /
              port: default-port
              httpHeaders:
                - name: X-k8s-Header
                  value: readiness
          livenessProbe:
            failureThreshold: 3
            timeoutSeconds: 5
            successThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 20
            httpGet:
              path: /
              port: default-port
              httpHeaders:
                - name: X-k8s-Header
                  value: readiness
      imagePullSecrets:
        - name: internal-harbor