apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy.yaml
  - ingress.yaml
  - pv-pvc.yaml
  - service.yaml
  - registry.yaml
labels:
  - includeSelectors: true
    pairs:
      app: yuito-site